# Automatically generated by "pub global run bazel:bazelify".
# DO NOT MODIFY BY HAND

PUB_PACKAGE_NAME = "example"

# Generated automatically for package:example|pubspec.yaml
def bazelify():
    native.new_local_repository(
        name = "args",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/args-0.13.7/",
        build_file = ".bazelify/args.BUILD",
    )
    native.new_local_repository(
        name = "async",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/async-1.11.3/",
        build_file = ".bazelify/async.BUILD",
    )
    native.new_local_repository(
        name = "barback",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/barback-0.15.2+9/",
        build_file = ".bazelify/barback.BUILD",
    )
    native.new_local_repository(
        name = "browser",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/browser-0.10.0+2/",
        build_file = ".bazelify/browser.BUILD",
    )
    native.new_local_repository(
        name = "collection",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/collection-1.9.1/",
        build_file = ".bazelify/collection.BUILD",
    )
    native.new_local_repository(
        name = "csslib",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/csslib-0.13.2+2/",
        build_file = ".bazelify/csslib.BUILD",
    )
    native.new_local_repository(
        name = "dart_to_js_script_rewriter",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/dart_to_js_script_rewriter-1.0.2/",
        build_file = ".bazelify/dart_to_js_script_rewriter.BUILD",
    )
    native.new_local_repository(
        name = "html",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/html-0.13.0/",
        build_file = ".bazelify/html.BUILD",
    )
    native.new_local_repository(
        name = "logging",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/logging-0.11.3+1/",
        build_file = ".bazelify/logging.BUILD",
    )
    native.new_local_repository(
        name = "path",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/path-1.4.0/",
        build_file = ".bazelify/path.BUILD",
    )
    native.new_local_repository(
        name = "pool",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/pool-1.2.4/",
        build_file = ".bazelify/pool.BUILD",
    )
    native.new_local_repository(
        name = "source_span",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/source_span-1.3.0/",
        build_file = ".bazelify/source_span.BUILD",
    )
    native.new_local_repository(
        name = "stack_trace",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.7.0/",
        build_file = ".bazelify/stack_trace.BUILD",
    )
    native.new_local_repository(
        name = "utf",
        path = "/usr/local/google/home/nshahan/.pub-cache/hosted/pub.dartlang.org/utf-0.9.0+3/",
        build_file = ".bazelify/utf.BUILD",
    )
    native.new_local_repository(
        name = "example",
        path = "/usr/local/google/home/nshahan/code/dart-web-test/example/",
        build_file = ".bazelify/example.BUILD",
    )
