name: 'example'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Nicholas Shahan <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  path:
  quiver:

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  webdriver: '^1.2.1'
  test: '^0.12.17'

transformers:
- dart_to_js_script_rewriter
