name: 'simple'
version: 0.0.1
description: An absolute bare-bones library.
#author: Nicholas Shahan <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  path:
  quiver: